trigger:
  branches:
    include:
      - '*' # to trigger this pipeline on changes to all branches

pool:
  vmImage: 'ubuntu-latest'

stages:
  # Sync code with Github
  - stage: GithubSync
    jobs:
      - job:
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0 # get full commit history

          - script: |

              echo "Source branch (raw): $(Build.SourceBranch)"

              # Strip 'refs/heads/' to get the clean branch name
              BRANCH_NAME=$(echo "$(Build.SourceBranch)" | sed 's#refs/heads/##')

              echo "Cleaned branch name: $BRANCH_NAME"

              echo "Adding GitHub remote"
              git remote add github https://$(GITHUB_PAT)@github.com/marsdensoftware/aem-edge-forms-3
              echo "GitHub remote success"

              # Fetch the latest changes from both origin and github remotes
              git fetch origin

              #git fetch github
              # Checkout the current branch being built
              #echo "Checking out the current branch"
              #git checkout $(Build.SourceBranchName)

              #echo "Merging destination branch into current branch"
              #git merge github/$(Build.SourceBranchName) --strategy-option ours || echo "Merge conflicts resolved by overriding source branch changes"

              echo "Pushing HEAD to GitHub branch: $BRANCH_NAME"
              git push --force github HEAD:$(Build.SourceBranch)

            displayName: 'Push Code to GitHub'
            #env:
            #GITHUB_SSH_PRIVATE_KEY: $(GITHUB_SSH_PRIVATE_KEY)
  # Build steps
  - stage: Build
    jobs:
      - job:
        steps:
          - script: |
              npm ci
              npm run build:css
            displayName: Build CSS
          - publish: $(System.DefaultWorkingDirectory)/styles
            artifact: CSSBuilt
          - download: current
            artifact: CSSBuilt
            patterns: '**/styles/main.css'
